### ISSUE TITLE
CancelAllNotifications() is not working Android 7.0 or below

### ISSUE THREAD

**Issue by githubsoooh** [Unity-Technologies/NotificationsSamples#29] opened 2019-11-08 12:39 UTC
but 8.0 or above are working

**Comment by julianunity** [comment] 2019-12-23 17:00
- Pixel 3 (Android version 10) 
ZD: 757060

**Comment by OrestNecros** [comment] 2020-02-14 10:59
Same issue. Due to this behavior notifications are not cleared and duplicates can be delivered. 
Will try to manually track existence of notifications based on identifiers and handle them that way. 
Device:
OnePlus 3
Android: 6.0.1

**Comment by vaidasma** [comment] 2021-06-10 10:30
Hello, does the issue still reoccur on the latest notification package (1.4.1) ?

Both sending and cancelling notification works on the following devices tested:
• Xiaomi Mi 5s (MI 5s), OS: 6.0.1
• Samsung Galaxy S8 USA (SM-G950U), OS: 7.0.0

I'm closing the issue for now, however, if it still does not work for you, please contact us again and provide the names of the devices that are able to reproduce this issue!

**Closed as completed by vaidasma** 2021-06-10 10:30 UTC
