### ISSUE TITLE
Notification small_icon and large_icon missing if rescheduled on android

### ISSUE THREAD

**Issue by inxidious** [Unity-Technologies/NotificationsSamples#20] opened 2019-09-12 09:39 UTC
It works fine if the notification is not being rescheduled

**Comment by AnthonyDemanueleFSG** [comment] 2019-10-30 09:52
Is your issue similar to this?

![NotificationsBug](https://user-images.githubusercontent.com/49918064/67847518-4dc8f500-fb03-11e9-83ac-69f96bd45f5e.png)

**Comment by inxidious** [comment] 2019-10-31 08:13
> Is your issue similar to this?
> 
> ![NotificationsBug](https://user-images.githubusercontent.com/49918064/67847518-4dc8f500-fb03-11e9-83ac-69f96bd45f5e.png)

No, in my case, the large icon is completely invisible and the small icon used is the game icon instead of specified small icon in the code

**Comment by AnthonyDemanueleFSG** [comment] 2019-10-31 12:12
ok @inxidious, thanks.

**Comment by ghost** [comment] 2020-05-05 17:56
Did they ever fix this?

**Comment by inxidious** [comment] 2020-05-06 04:20
> Did they ever fix this?

i updated to latest version on March 2020, still not fixed and there were other issues beside this one, so i switched to UTNotifications

**Comment by lune856** [comment] 2020-07-06 14:56
Same here. With rescheduled notifications Small/Large icons disappear and show default Unity icon.
Any fix for this?

**Comment by vaidasma** [comment] 2021-06-10 12:04
Hey, could anybody clarify that this is still reproducible in Notification package 1.4.1 ? 

We're not able to reproduce it so far. 
Does the issue happen when notification has been rescheduled after the device restart?

Please provide the devices you've used, their OS, as well as Unity editor that you've used

**Comment by aurimasc** [comment] 2021-09-08 12:41
This one should be fixed in master.

**Closed as completed by aurimasc** 2021-09-08 12:41 UTC

**Comment by K0ST4S** [comment] 2023-02-26 15:02
I get this problem with my Samsung Galaxy A51.
Android version: 11
Unity version: 2021.3.0f1
Package version: 2.0.2

To replicate with sample project:

Select "Everything" mode. Make notifications schedule a few minutes after game launch.
After building and launching pause and unpause app twince before notifications are delivered.
Pause app.
Await notifications.
